#
# Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN). 2016-2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

mfa:
  multi-factor-settings-btn-enabled: ${IAM_TOTP_MFA_ENABLE_MFA_SETTINGS_BUTTON:true}
  # Please store this KEY securly & safetly
  password-to-encrypt-and-decrypt: ${IAM_TOTP_MFA_PASSWORD_TO_ENCRYPT_AND_DECRYPT:define_me_please}
  # ONLY provide the previous KEY if you are rotating to a new KEY above.
  # Leave this blank if no KEY rotation is happening.
  old-password-to-decrypt: ${IAM_TOTP_MFA_OLD_PASSWORD_TO_DECRYPT:}
  multi-factor-mandatory:  ${IAM_MULTI_FACTOR_MANDATORY:false}