FROM eclipse-temurin:17 AS builder

RUN apt-get update && apt-get upgrade -y && \
  mkdir /indigo-iam
WORKDIR /indigo-iam
COPY iam-login-service.war /indigo-iam/
RUN java -Djarmode=layertools -jar iam-login-service.war extract

FROM eclipse-temurin:17
RUN mkdir /indigo-iam
WORKDIR /indigo-iam
COPY --from=builder indigo-iam/dependencies/ ./
COPY --from=builder indigo-iam/spring-boot-loader/ ./
COPY --from=builder indigo-iam/snapshot-dependencies/ ./
COPY --from=builder indigo-iam/application/ ./

RUN apt-get update && apt-get upgrade -y && \
  apt-get install -y zip && \
  zip -d WEB-INF/lib/angular-ui-bootstrap-2.5.6.jar META-INF/resources/webjars/angular-ui-bootstrap/2.5.6/dist/.DS_Store

RUN if [ -f WEB-INF/classes/keystore.jwks ]; then \
    echo "ERROR: keystore.jwks should not be present in the image"; \
    exit 1; \
  fi

CMD ["/bin/sh", "-c", "java ${IAM_JAVA_OPTS} org.springframework.boot.loader.WarLauncher"]
